# Generated by Django 4.0.5 on 2022-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='hobbies',
            name='profile',
            field=models.ManyToManyField(to='user_management.userprofile'),
        ),
    ]
