# Generated by Django 4.0.5 on 2022-06-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_userprofile_hobbies_hobbies_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
